// ==========================================
// ASTU MSJ Summer Bootcamp - Initial Mock State
// ==========================================

export const initialBatches = [
  {
    _id: 'batch_1',
    name: 'Frontend Track (Summer 2026)',
    track: 'Frontend Development',
    description: 'HTML5/CSS3, Modern JavaScript ES6+, React.js, TailwindCSS & Component Architecture',
    startDate: '2026-07-01',
    endDate: '2026-08-30',
    isActive: true,
    mentorIds: ['usr_m1'],
    studentCount: 42,
  },
  {
    _id: 'batch_2',
    name: 'Backend Engineering (Summer 2026)',
    track: 'Backend Engineering',
    description: 'Node.js runtime, Express.js REST APIs, MongoDB Mongoose modeling, Auth & Cloud deployment',
    startDate: '2026-07-01',
    endDate: '2026-08-30',
    isActive: true,
    mentorIds: ['usr_m2'],
    studentCount: 38,
  },
  {
    _id: 'batch_3',
    name: 'Full-Stack MERN (Summer 2026)',
    track: 'Full-Stack MERN',
    description: 'End-to-end full stack web applications integrating React frontend with Express/MongoDB backend',
    startDate: '2026-07-01',
    endDate: '2026-08-30',
    isActive: true,
    mentorIds: ['usr_m1', 'usr_m2'],
    studentCount: 48,
  },
];

export const initialUsers = [
  {
    _id: 'usr_a1',
    userId: 'msj-adm-1-2026',
    fullName: 'Nafyad Admin',
    email: 'admin@astu.edu.et',
    role: 'admin',
    phone: '+251911223344',
    isActive: true,
    batchId: null,
    createdAt: '2026-06-15',
  },
  {
    _id: 'usr_m1',
    userId: 'msj-mnt-1-2026',
    fullName: 'Dawit Tesfaye',
    email: 'dawit.mentor@astu.edu.et',
    role: 'mentor',
    phone: '+251922334455',
    isActive: true,
    batchId: 'batch_1',
    createdAt: '2026-06-20',
  },
  {
    _id: 'usr_m2',
    userId: 'msj-mnt-2-2026',
    fullName: 'Yonas Bekele',
    email: 'yonas.mentor@astu.edu.et',
    role: 'mentor',
    phone: '+251933445566',
    isActive: true,
    batchId: 'batch_2',
    createdAt: '2026-06-20',
  },
  {
    _id: 'usr_s1',
    userId: 'msj-st-1-2026',
    fullName: 'Abebe Bikila',
    email: 'abebe.b@astu.edu.et',
    role: 'student',
    phone: '+251944556677',
    isActive: true,
    batchId: 'batch_1',
    attendance: 96,
    progress: 'Completed',
    createdAt: '2026-06-25',
  },
  {
    _id: 'usr_s2',
    userId: 'msj-st-2-2026',
    fullName: 'Almaz Ayana',
    email: 'almaz.a@astu.edu.et',
    role: 'student',
    phone: '+251955667788',
    isActive: true,
    batchId: 'batch_3',
    attendance: 88,
    progress: 'In Progress',
    createdAt: '2026-06-25',
  },
  {
    _id: 'usr_s3',
    userId: 'msj-st-3-2026',
    fullName: 'Derartu Tulu',
    email: 'derartu.t@astu.edu.et',
    role: 'student',
    phone: '+251966778899',
    isActive: true,
    batchId: 'batch_2',
    attendance: 71,
    progress: 'Needs Improvement',
    createdAt: '2026-06-26',
  },
  {
    _id: 'usr_s4',
    userId: 'msj-st-4-2026',
    fullName: 'Kenenisa Bekele',
    email: 'kenenisa.b@astu.edu.et',
    role: 'student',
    phone: '+251977889900',
    isActive: false,
    batchId: 'batch_3',
    attendance: 98,
    progress: 'Completed',
    createdAt: '2026-06-27',
  },
  {
    _id: 'usr_s5',
    userId: 'msj-st-5-2026',
    fullName: 'Fatima Mohammed',
    email: 'fatima.m@astu.edu.et',
    role: 'student',
    phone: '+251988990011',
    isActive: true,
    batchId: 'batch_1',
    attendance: 92,
    progress: 'In Progress',
    createdAt: '2026-06-28',
  },
];

export const initialApplications = [
  {
    _id: 'app_1',
    fullName: 'Sintayehu Kebede',
    email: 'sintayehu.k@astu.edu.et',
    phone: '+251911445566',
    telegramHandle: '@sinta_dev',
    gender: 'Male',
    department: 'Software Engineering',
    year: '3rd Year',
    university: 'ASTU',
    githubUrl: 'https://github.com/sintayehu-k',
    codeforcesUrl: 'https://codeforces.com/profile/sinta_coder',
    leetcodeUrl: 'https://leetcode.com/u/sintayehu_k',
    motivation: 'I want to master React and scalable REST API development to prepare for junior developer internships and compete in hackathons.',
    roleAtApplication: 'student',
    trackPreference: 'Frontend Track (Summer 2026)',
    status: 'Pending',
    createdAt: '2026-08-18T10:30:00Z',
  },
  {
    _id: 'app_2',
    fullName: 'Meron Tadesse',
    email: 'meron.t@astu.edu.et',
    phone: '+251922556677',
    telegramHandle: '@meron_t',
    gender: 'Female',
    department: 'Computer Science & Engineering',
    year: '4th Year',
    university: 'ASTU',
    githubUrl: 'https://github.com/meron-tad',
    codeforcesUrl: '',
    leetcodeUrl: 'https://leetcode.com/u/meron_cse',
    motivation: 'Passionate about backend microservices, MongoDB aggregation pipelines, and cloud deployment pipelines on AWS/Render.',
    roleAtApplication: 'student',
    trackPreference: 'Backend Engineering (Summer 2026)',
    status: 'Accepted',
    createdAt: '2026-08-17T14:15:00Z',
  },
  {
    _id: 'app_3',
    fullName: 'Kidus Hailu',
    email: 'kidus.h@aau.edu.et',
    phone: '+251933667788',
    telegramHandle: '@kidus_code',
    gender: 'Male',
    department: 'Information Technology',
    year: '2nd Year',
    university: 'AAU (Guest Applicant)',
    githubUrl: 'https://github.com/kidus-hailu',
    codeforcesUrl: 'https://codeforces.com/profile/kidus_h',
    leetcodeUrl: '',
    motivation: 'Looking to deepen my JavaScript full-stack skills and collaborate with peer students on impactful software projects.',
    roleAtApplication: 'student',
    trackPreference: 'Full-Stack MERN (Summer 2026)',
    status: 'Pending',
    createdAt: '2026-08-18T16:45:00Z',
  },
  {
    _id: 'app_4',
    fullName: 'Hanan Abdi',
    email: 'hanan.abdi@astu.edu.et',
    phone: '+251944778899',
    telegramHandle: '@hanan_dev',
    gender: 'Female',
    department: 'Electrical & Computer Engineering',
    year: '3rd Year',
    university: 'ASTU',
    githubUrl: 'https://github.com/hanan-abdi',
    codeforcesUrl: '',
    leetcodeUrl: '',
    motivation: 'Interested in mastering UI component design systems with Tailwind and modern React state management patterns.',
    roleAtApplication: 'student',
    trackPreference: 'Frontend Track (Summer 2026)',
    status: 'Rejected',
    createdAt: '2026-08-15T09:00:00Z',
  },
];

export const initialAttendanceRecords = [
  {
    _id: 'att_1',
    studentId: 'usr_s1',
    studentName: 'Abebe Bikila',
    batchId: 'batch_1',
    date: '2026-08-18',
    status: 'present',
    markedBy: 'usr_m1',
    note: 'Active participation in React State lab',
  },
  {
    _id: 'att_2',
    studentId: 'usr_s5',
    studentName: 'Fatima Mohammed',
    batchId: 'batch_1',
    date: '2026-08-18',
    status: 'present',
    markedBy: 'usr_m1',
    note: '',
  },
  {
    _id: 'att_3',
    studentId: 'usr_s3',
    studentName: 'Derartu Tulu',
    batchId: 'batch_2',
    date: '2026-08-18',
    status: 'absent',
    markedBy: 'usr_m2',
    note: 'Sick leave reported via Telegram',
  },
  {
    _id: 'att_4',
    studentId: 'usr_s2',
    studentName: 'Almaz Ayana',
    batchId: 'batch_3',
    date: '2026-08-18',
    status: 'present',
    markedBy: 'usr_m1',
    note: '',
  },
  {
    _id: 'att_5',
    studentId: 'usr_s4',
    studentName: 'Kenenisa Bekele',
    batchId: 'batch_3',
    date: '2026-08-18',
    status: 'late',
    markedBy: 'usr_m1',
    note: 'Arrived 15 mins late due to lab transport',
  },
];

export const initialAssignments = [
  {
    _id: 'asg_1',
    title: 'Interactive Dashboard with React & Tailwind',
    batchId: 'batch_1',
    batchName: 'Frontend Track (Summer 2026)',
    deadline: '2026-08-25T23:59:00Z',
    maxScore: 100,
    description: 'Construct a responsive multi-page dashboard application incorporating Lucide icons, responsive navigation drawers, and reusable card components.',
    instructions: '1. Clone the starter repo.\n2. Implement React router routes.\n3. Ensure dark/light mode contrast compliance.\n4. Deploy to Vercel/Netlify and submit both GitHub and live URLs.',
    createdAt: '2026-08-15T12:00:00Z',
  },
  {
    _id: 'asg_2',
    title: 'JWT Authentication & Role-Based Middleware REST API',
    batchId: 'batch_2',
    batchName: 'Backend Engineering (Summer 2026)',
    deadline: '2026-08-24T23:59:00Z',
    maxScore: 100,
    description: 'Build a secure Express.js REST API with user registration, bcrypt password hashing, JWT cookies, and admin/mentor/student authorization guards.',
    instructions: '1. Setup Mongoose user schemas.\n2. Write protect & restrictTo middlewares.\n3. Validate request payloads using Joi or Express-validator.\n4. Include Postman collection in repo.',
    createdAt: '2026-08-14T09:00:00Z',
  },
  {
    _id: 'asg_3',
    title: 'Full-Stack Task & Notes Web Application',
    batchId: 'batch_3',
    batchName: 'Full-Stack MERN (Summer 2026)',
    deadline: '2026-08-28T23:59:00Z',
    maxScore: 150,
    description: 'Design and deploy a complete MERN stack application connecting a React frontend to Express/MongoDB backend with CRUD capabilities.',
    instructions: '1. Connect React Axios client to Express backend.\n2. Implement optimistic UI updates.\n3. Deploy backend to Render and frontend to Vercel.',
    createdAt: '2026-08-16T14:30:00Z',
  },
];

export const initialSubmissions = [
  {
    _id: 'sub_1',
    assignmentId: 'asg_1',
    assignmentTitle: 'Interactive Dashboard with React & Tailwind',
    studentId: 'usr_s1',
    studentName: 'Abebe Bikila',
    studentEmail: 'abebe.b@astu.edu.et',
    githubUrl: 'https://github.com/abebe-b/react-tailwind-dashboard',
    liveDemoUrl: 'https://abebe-dashboard-demo.vercel.app',
    notes: 'Completed all required pages including mobile responsive drawer and custom dark mode palette.',
    score: 95,
    feedback: 'Excellent component decomposition and clean Tailwind classes! Great attention to responsiveness.',
    status: 'graded',
    submittedAt: '2026-08-17T18:20:00Z',
    gradedAt: '2026-08-18T10:00:00Z',
  },
  {
    _id: 'sub_2',
    assignmentId: 'asg_2',
    assignmentTitle: 'JWT Authentication & Role-Based Middleware REST API',
    studentId: 'usr_s3',
    studentName: 'Derartu Tulu',
    studentEmail: 'derartu.t@astu.edu.et',
    githubUrl: 'https://github.com/derartu-t/express-auth-api',
    liveDemoUrl: '',
    notes: 'Implemented cookie auth and Joi schemas. Need help with token expiration edge cases.',
    score: null,
    feedback: '',
    status: 'submitted',
    submittedAt: '2026-08-18T16:00:00Z',
    gradedAt: null,
  },
  {
    _id: 'sub_3',
    assignmentId: 'asg_3',
    assignmentTitle: 'Full-Stack Task & Notes Web Application',
    studentId: 'usr_s2',
    studentName: 'Almaz Ayana',
    studentEmail: 'almaz.a@astu.edu.et',
    githubUrl: 'https://github.com/almaz-a/mern-task-app',
    liveDemoUrl: 'https://almaz-mern-task.vercel.app',
    notes: 'Backend hosted on Render, MongoDB Atlas database connected with full CORS support.',
    score: 142,
    feedback: 'Outstanding implementation! Database indexes and error handling middleware are very well structured.',
    status: 'graded',
    submittedAt: '2026-08-18T11:45:00Z',
    gradedAt: '2026-08-18T15:30:00Z',
  },
];

export const initialAnnouncements = [
  {
    _id: 'ann_1',
    title: 'Mid-Bootcamp Project Submission & PR Review Guidelines',
    targetAudience: 'all',
    batchId: null,
    urgent: true,
    author: 'Nafyad (Lead Admin)',
    publishDate: '2026-08-18',
    content: 'All students must push their intermediate project repos to GitHub and submit the PR link before Friday 11:59 PM. Mentors will conduct 1-on-1 code reviews over the weekend in the main computer lab.',
  },
  {
    _id: 'ann_2',
    title: 'Guest Speaker Session: Senior Engineer from Chapa Payments',
    targetAudience: 'batch',
    batchId: 'batch_3',
    urgent: false,
    author: 'Admin Office',
    publishDate: '2026-08-16',
    content: 'Join us this Wednesday at 3:00 PM in Lab 3 for an interactive session on integrating modern payment gateways and fintech APIs in Ethiopian web applications.',
  },
  {
    _id: 'ann_3',
    title: 'Weekend Server Maintenance & Lab Network Upgrades',
    targetAudience: 'students',
    batchId: null,
    urgent: false,
    author: 'Admin Office',
    publishDate: '2026-08-14',
    content: 'The ASTU computer lab local network and database test instances will undergo routine maintenance on Saturday morning (8:00 AM - 12:00 PM). Cloud instances will remain operational.',
  },
];

export const initialCurriculumSchedules = [
  {
    _id: 'sch_1',
    weekNumber: 1,
    title: 'Foundations of Modern Web Architecture & Git Workflows',
    topics: [
      { day: 'Day 1', topicName: 'Git & GitHub Collaboration, PRs, Branching Strategies', date: '2026-07-01' },
      { day: 'Day 2', topicName: 'HTML5 Semantic Markup & CSS3 Layout Engines (Flexbox & Grid)', date: '2026-07-02' },
      { day: 'Day 3', topicName: 'Modern JavaScript (ES6+, Promises, Async/Await, Array Methods)', date: '2026-07-03' },
      { day: 'Day 4', topicName: 'DOM Manipulation, Fetch API & Asynchronous Programming', date: '2026-07-04' },
      { day: 'Day 5', topicName: 'Week 1 Mini-Project: Interactive Client Application', date: '2026-07-05' },
    ],
  },
  {
    _id: 'sch_2',
    weekNumber: 2,
    title: 'React Fundamentals & Component-Driven UI Engineering',
    topics: [
      { day: 'Day 1', topicName: 'Vite Setup, JSX Syntax & Component Life Cycle', date: '2026-07-08' },
      { day: 'Day 2', topicName: 'State Management: useState, useEffect & Custom Hooks', date: '2026-07-09' },
      { day: 'Day 3', topicName: 'TailwindCSS Styling System & Responsive Design Patterns', date: '2026-07-10' },
      { day: 'Day 4', topicName: 'Client-Side Routing with React Router v6', date: '2026-07-11' },
      { day: 'Day 5', topicName: 'Week 2 Lab: Multi-Page Dashboard UI', date: '2026-07-12' },
    ],
  },
  {
    _id: 'sch_3',
    weekNumber: 3,
    title: 'Backend API Engineering with Node.js, Express & MongoDB',
    topics: [
      { day: 'Day 1', topicName: 'Node.js Event Loop, HTTP Module & Express Setup', date: '2026-07-15' },
      { day: 'Day 2', topicName: 'RESTful API Routing, Controllers & Middleware Architecture', date: '2026-07-16' },
      { day: 'Day 3', topicName: 'MongoDB Atlas & Mongoose Schemas, Validation & Indexing', date: '2026-07-17' },
      { day: 'Day 4', topicName: 'JWT Authentication, Password Hashing & Role-Based Access Control', date: '2026-07-18' },
      { day: 'Day 5', topicName: 'Week 3 Lab: Production-Ready Auth & CRUD API', date: '2026-07-19' },
    ],
  },
];

export const initialResources = [
  {
    _id: 'res_1',
    title: 'Official React Documentation & Interactive Tutorials',
    description: 'Comprehensive modern guide to React components, hooks, and performance optimization.',
    link: 'https://react.dev',
    topic: 'Frontend Development',
    mentorName: 'Dawit Tesfaye',
    createdAt: '2026-07-02',
  },
  {
    _id: 'res_2',
    title: 'Mongoose ODM Schema Design & Population Patterns',
    description: 'Deep dive into Mongoose modeling, references, compound indexes, and pre/post hooks.',
    link: 'https://mongoosejs.com/docs/guide.html',
    topic: 'Backend Engineering',
    mentorName: 'Yonas Bekele',
    createdAt: '2026-07-05',
  },
  {
    _id: 'res_3',
    title: 'TailwindCSS Component System & Utility Class Cheatsheet',
    description: 'Official Tailwind documentation for responsive grid layouts, animations, and custom color tokens.',
    link: 'https://tailwindcss.com/docs',
    topic: 'Frontend Styling',
    mentorName: 'Dawit Tesfaye',
    createdAt: '2026-07-03',
  },
  {
    _id: 'res_4',
    title: 'JWT Authentication & Security Best Practices Cheatsheet',
    description: 'OWASP recommendations on secure token storage, HTTP-only cookies, and CSRF protection.',
    link: 'https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html',
    topic: 'Security & Auth',
    mentorName: 'Nafyad Admin',
    createdAt: '2026-07-10',
  },
];

// Fallback statistics helper
export const getAdminStats = (users = initialUsers, batches = initialBatches, applications = initialApplications, submissions = initialSubmissions) => {
  const students = users.filter((u) => u.role === 'student');
  const mentors = users.filter((u) => u.role === 'mentor');
  const pendingApps = applications.filter((a) => a.status === 'Pending').length;
  const gradedSubmissions = submissions.filter((s) => s.status === 'graded').length;

  return {
    totalStudents: students.length,
    totalMentors: mentors.length,
    totalBatches: batches.length,
    pendingApplications: pendingApps,
    avgAttendance: '92.4%',
    assignmentCompletion: `${submissions.length > 0 ? Math.round((gradedSubmissions / submissions.length) * 100) : 88}%`,
    totalSubmissions: submissions.length,
  };
};
